swagger: '2.0'
######################################################
# Prolog
######################################################
info:
  version: "1.0.0"
  title: "WSO2 Identity Server Resource Management Rest API"
  description: |
    This document specifies a **Configurations Management RESTfulAPI** for WSO2 **Identity Server** .
    It is written with [swagger 2](http://swagger.io/).
  contact:
    name: "WSO2"
    url: "http://wso2.com/products/identity-server/"
    email: "architecture@wso2.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

######################################################
# The fixed parts of the URLs of the API
######################################################

# The schemes supported by the API
schemes:
- https

# The domain of the API.
# This is configured by the customer during deployment.
# The given host is just an example.
# host: apis.is.com

# The base path of the API.
# Will be prefixed to all paths.
# if the tenant domain is carbon.super basepath can be /api/identity/config-mgt/v1.0 like this too.

basePath: /t/{tenant-domain}/api/identity/config-mgt/v1.0

# The following media types can be passed as input in message bodies of the API.
# The actual media type must be specified in the Content-Type header field of the request.
# The default is json, i.e. the Content-Type header is not needed to
# be set, but supporting it serves extensibility.
consumes:
- application/json

# The following media types may be passed as output in message bodies of the API.
# The media type(s) consumable by the requester is specified in the Accept header field
# of the corresponding request.
# The actual media type returned will be specified in the Content-Type header field
# of the of the response.
# The default of the Accept header is json, i.e. there is not needed to
# set the value, but supporting it serves extensibility.
produces:
- application/json
paths:
  # Endpoint used to create resource types
  "/resource-type":
    post:
      description: |
        This API is used to create a new resource type.
      x-wso2-request:
      x-wso2-curl:
      x-wso2-response:
      summary: |
        Create the resource type.
      parameters:
      - name: type
        in: body
        description: This represents the resource type to be added.
        required: true
        schema:
          $ref: '#/definitions/ResourceTypeCreate'
      responses:
        201:
          description: Successful response
          schema:
            $ref: '#/definitions/ResourceType'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        409:
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
      - Type
    put:
      description: |
        This API is used to create or replace a new resource type.
      x-wso2-request:
      x-wso2-curl:
      x-wso2-response:
      summary: |
        Create or replace the resource type.
      parameters:
      - name: type
        in: body
        description: This represents the resource type to be added.
        required: true
        schema:
          $ref: '#/definitions/ResourceTypeCreate'
      responses:
        201:
          description: Successful response
          schema:
            $ref: '#/definitions/ResourceType'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        409:
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
      - Type
    patch:
      description: |
        This API is used to update an existing resource type.
      x-wso2-request:
      x-wso2-curl:
      x-wso2-response:
      summary: |
        Update existing resource type.
      parameters:
      - name: type
        in: body
        description: This represents the resource type to update the existing.
        required: true
        schema:
          $ref: '#/definitions/ResourceTypeCreate'
      responses:
        201:
          description: Successful response
          schema:
            $ref: '#/definitions/ResourceType'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        409:
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
      - Type
    get:
      description: |
        This API is used to get an existing resource type.
      x-wso2-request:
      x-wso2-curl:
      x-wso2-response:
      summary: |
        Get the resource type.
      parameters:
      - name: name
        in: query
        description: This represents the resource type to be retrieved.
        type: string
      - name: id
        in: query
        description: This represents the resource type to be retrieved.
        type: string
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/ResourceType'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        409:
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
      - Type
    delete:
      description: |
        This API is used to delete an existing resource type.
      x-wso2-request:
      x-wso2-curl:
      x-wso2-response:
      summary: |
        Revoke resource type.
      parameters:
      - name: name
        in: query
        description: This represents the resource type to be retrieved.
        type: string
      - name: id
        in: query
        description: This represents the resource type to be retrieved.
        type: string
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        409:
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
      - Type

  # Endpoint used to add tenant resources
  "/resource":
    get:
      description: |
        This API is used to retrieve resources for the tenant domain based on the optional search parameters.
      x-wso2-request:
      x-wso2-curl:
      x-wso2-response:
      summary: |
        Retrieve resources based on the optional search parmeters.
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ResourceSearchResponse'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
      - Resource

  "/resource/{name}":
    post:
      description: |
        This API is used to store the resource given by the user.
      x-wso2-request:
      x-wso2-curl:
      x-wso2-response:
      summary: |
        Create the resource
      # post parameters:
      parameters:
      - name: name
        in: path
        description:  This represents the name of the resource to be added.
        required: true
        type: 'string'
      - name: resource
        in: body
        description:  This represents the resource that needs to be added.
        required: true
        schema:
          $ref: '#/definitions/Resource'
      responses:
        201:
          description: Successful response
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        409:
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
      - Resource
    put:
      description: |
        This API is used to store or replace the resource given by the user.
      x-wso2-request:
      x-wso2-curl:
      x-wso2-response:
      summary: |
        Add or Replace the resource
      # put parameters:
      parameters:
      - name: name
        in: path
        description:  This represents the name of the resource to be added or replaced.
        required: true
        type: 'string'
      - name: resource
        in: body
        description:  This represents the resource that need to be added or replaced.
        required: true
        schema:
          $ref: '#/definitions/Resource'
      responses:
        201:
          description: Successful response
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
      - Resource
    patch:
      description: |
        This API is used to update an existing resource given by the user.
      x-wso2-request:
      x-wso2-curl:
      x-wso2-response:
      summary: |
        Update existing resource
      # patch parameters:
      parameters:
      - name: name
        in: path
        description:  This represents the name of the resource to be added or updated.
        required: true
        type: 'string'
      - name: resource
        in: body
        description:  This represents the resource that needs to be updated.
        required: true
        schema:
          $ref: '#/definitions/Resource'
      responses:
        201:
          description: Successful response
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
      - Resource
    get:
      description: |
        This API is used to retrieve a resource based on optional search filters.
      x-wso2-request:
      x-wso2-curl:
      x-wso2-response:
      summary: |
        Retrieve the resource based on optional search parameters.
      parameters:
      - name: name
        in: path
        description:  This represents the name of the resource to be retrieved.
        required: true
        type: 'string'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ResourceSearchResponse'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
      - Resource
    delete:
      description: |
        This API is used to revoke a resource in the tenant domain given by the user.
      x-wso2-request:
      x-wso2-curl:
      x-wso2-response:
      summary: |
        Revoke the resource
      parameters:
      - name: name
        in: path
        description:  This represents the name of the resource to be retrieved.
        required: true
        type: 'string'
      responses:
        200:
          description: OK
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server Error
          schema:
            $ref: '#/definitions/Error'
      tags:
      - Resource

definitions:
  #-----------------------------------------------------
  # The Error Response  object
  #-----------------------------------------------------
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      description:
        type: string
  #-----------------------------------------------------
  # Resource Attribute Object
  #-----------------------------------------------------
  Attribute:
    type: object
    required:
    - key
    - value
    properties:
      key:
        type: string
      value:
        type: string
  #-----------------------------------------------------
  # Type Create object
  #-----------------------------------------------------
  ResourceTypeCreate:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
  #-----------------------------------------------------
  # Type Request object
  #-----------------------------------------------------
  ResourceTypeRequest:
    type: object
    properties:
      name:
        type: string
      id:
        type: string
  #-----------------------------------------------------
  # Type object
  #-----------------------------------------------------
  ResourceType:
    type: object
    properties:
      name:
        type: string
      id:
        type: string
      description:
        type: string
  #-----------------------------------------------------
  # Resource object
  #-----------------------------------------------------
  Resource:
    type: object
    required:
    - resourceName
    - type
    properties:
      resourceName:
        type: string
      attributes:
        type: array
        items:
          $ref: '#/definitions/Attribute'
      type:
        $ref: '#/definitions/ResourceType'
      file:
        type: object
        properties:
          value:
            type: string
  #-----------------------------------------------------
  # Resource Search Response Element object
  #-----------------------------------------------------
  ResourceSearchResponseElement:
    type: object
    required:
    - resource
    - tenantId
    properties:
      resource:
        $ref: '#/definitions/Resource'
      tenantId:
        type: string
  #-----------------------------------------------------
  # Resource Search Response object
  #-----------------------------------------------------
  ResourceSearchResponse:
    type: object
    required:
    - resources
    properties:
      resources:
        type: array
        items:
          $ref: '#/definitions/ResourceSearchResponseElement'
